### ISSUE TITLE
What is single_attention_param?

### ISSUE THREAD

**Issue by yanghanxy** [codekansas/keras-language-modeling#40]
Could you explain what is the meaning for setting` single_attention_param=True` in your AttentionLSTMWrapper()? 

Thanks!

**Comment by codekansas** [comment]
It was an option to change the type of attention to use. If `single_attention_param=True` then the attention component would consist of a single scalar value that would be multiplied at each timestep by the `h` vector of the LSTM to get the new `h` vector. Otherwise, if `single_attention_param=False` the attention component is a vector that is the same dimensionality as the `h` vector, and multiplies element-wise to get the new `h` vector at each timestep.
